# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20161107_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100, verbose_name='What is your ID?'),
        ),
    ]
